# Generated by Django 5.2.3 on 2025-06-15 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itinerary',
            name='user',
        ),
    ]
